import java.io.Serializable;
import java.util.*;


@SuppressWarnings("serial")
public class Item implements Serializable {
	//data to be stored in item class(Discription of the auction of the item)
	private int itemID;
	private String UserID; //username of the seller
	private int reservedPrice;
	private String title;
	private String description;
	private String startTime;
	private String endTime;
	private String keyWordChosen;
	private String[] keyWord = {"art", "clothes", "other"};
	private List<Bid> bids; //Stores itemID, userID and bid
	//initialised all the variables
	public Item(int itemID, String UserID, String title, int reservedPrice, String keyWord,  String startTime, String endTime, String description) {
		this.itemID=itemID;
		this.UserID=UserID;
		this.reservedPrice = reservedPrice;
		this.title=title;
		this.description=description;
		this.startTime=startTime;
		this.endTime=endTime;
		this.keyWordChosen=keyWord;
	}
	//To have autogenerated itemid
	public Item(String UserID, String title, int reservedPrice, 
			String keyWord, String startTime, String endTime, String description) {
		this.UserID=UserID;
		this.title=title;
		this.reservedPrice = reservedPrice;
		this.description=description;
		this.startTime=startTime;
		this.endTime=endTime;
		this.keyWordChosen=keyWord;
	}
	
	
	//Getter and setter methods
	
	
	public String getUserID() {
		return UserID;
	}

	public void setUserID(String UserID) {
		this.UserID = UserID;
	}

	public int getReservedPrice() {
		return reservedPrice;
	}

	public void setReservedPrice(int reservedPrice) {
		this.reservedPrice = reservedPrice;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getkeyWordChosen() {
		return keyWordChosen;
	}

	public void setkeyWordChosen(String keyWordChosen) {
		this.keyWordChosen = keyWordChosen;
	}

	public String[] getkeyWord() {
		return keyWord;
	}

	public void setkeyWord(String[] keyWord) {
		this.keyWord = keyWord;
	}

	public List<Bid> getBids() {
		return bids;
	}

	public void setBids(List<Bid> bids) {
		this.bids = bids;
	}

	public void setItemID(int itemID) {
		this.itemID = itemID;
	}


	
	public int getItemID() {
		return itemID;
	}
	
	public String[] getCategories(){
		return this.keyWord;
	}

}
